language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t puneetwarad/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true puneetwarad/react-test npm run test

after_success:
  - docker build -t puneetwarad/multi-client ./client
  - docker build -t puneetwarad/multi-nginx ./nginx
  - docker build -t puneetwarad/multi-server ./server
  - docker build -t puneetwarad/multi-worker ./worker
# Login to Docker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
# Docker Push
  - docker push puneetwarad/multi-client
  - docker push puneetwarad/multi-nginx
  - docker push puneetwarad/multi-server
  - docker push puneetwarad/multi-worker


